// Учебные материалы: [английский, русский перевод]
const LESSONS = {
  words: {
    title: 'Слова: базовые',
    type: 'words',
    items: [
      ['time', 'время'], ['people', 'люди'], ['year', 'год'], ['way', 'путь, способ'],
      ['day', 'день'], ['man', 'мужчина'], ['thing', 'вещь'], ['woman', 'женщина'],
      ['life', 'жизнь'], ['child', 'ребёнок'], ['world', 'мир'], ['school', 'школа'],
      ['family', 'семья'], ['student', 'студент'], ['group', 'группа'], ['country', 'страна'],
      ['problem', 'проблема'], ['hand', 'рука'], ['part', 'часть'], ['place', 'место'],
      ['week', 'неделя'], ['company', 'компания'], ['question', 'вопрос'], ['work', 'работа'],
      ['night', 'ночь'], ['point', 'точка, смысл'], ['home', 'дом'], ['water', 'вода'],
      ['room', 'комната'], ['mother', 'мать'], ['money', 'деньги'], ['story', 'история'],
      ['month', 'месяц'], ['book', 'книга'], ['job', 'работа, должность'], ['word', 'слово'],
      ['business', 'бизнес'], ['friend', 'друг'], ['city', 'город'], ['idea', 'идея'],
      ['know', 'знать'], ['think', 'думать'], ['make', 'делать'], ['want', 'хотеть'],
      ['give', 'давать'], ['find', 'находить'], ['tell', 'рассказывать'], ['become', 'становиться'],
      ['leave', 'уходить, оставлять'], ['feel', 'чувствовать'], ['bring', 'приносить'], ['begin', 'начинать'],
      ['keep', 'хранить, продолжать'], ['write', 'писать'], ['learn', 'учить'], ['change', 'менять'],
      ['understand', 'понимать'], ['remember', 'помнить'], ['believe', 'верить'], ['happen', 'случаться'],
      ['good', 'хороший'], ['new', 'новый'], ['first', 'первый'], ['last', 'последний'],
      ['long', 'длинный'], ['great', 'великий, отличный'], ['little', 'маленький'], ['different', 'разный'],
      ['small', 'маленький'], ['large', 'большой'], ['young', 'молодой'], ['important', 'важный'],
      ['early', 'ранний'], ['easy', 'лёгкий'], ['strong', 'сильный'], ['beautiful', 'красивый'],
      ['always', 'всегда'], ['never', 'никогда'], ['often', 'часто'], ['already', 'уже'],
    ],
  },
  verbs: {
    title: 'Слова: неправильные глаголы',
    type: 'words',
    items: [
      ['go went gone', 'идти'], ['see saw seen', 'видеть'], ['take took taken', 'брать'],
      ['come came come', 'приходить'], ['get got got', 'получать'], ['make made made', 'делать'],
      ['know knew known', 'знать'], ['think thought thought', 'думать'], ['give gave given', 'давать'],
      ['find found found', 'находить'], ['tell told told', 'рассказывать'], ['write wrote written', 'писать'],
      ['speak spoke spoken', 'говорить'], ['break broke broken', 'ломать'], ['buy bought bought', 'покупать'],
      ['bring brought brought', 'приносить'], ['teach taught taught', 'учить (кого-то)'], ['catch caught caught', 'ловить'],
      ['begin began begun', 'начинать'], ['drink drank drunk', 'пить'], ['swim swam swum', 'плавать'],
      ['eat ate eaten', 'есть'], ['fly flew flown', 'летать'], ['forget forgot forgotten', 'забывать'],
      ['choose chose chosen', 'выбирать'], ['wear wore worn', 'носить (одежду)'], ['sleep slept slept', 'спать'],
      ['leave left left', 'уходить'], ['meet met met', 'встречать'], ['pay paid paid', 'платить'],
    ],
  },
  a1: {
    title: 'Фразы: начальный уровень',
    type: 'phrases',
    items: [
      ['My name is Anna and I live in a small town.', 'Меня зовут Анна, и я живу в маленьком городе.'],
      ['I get up at seven o\'clock every morning.', 'Я встаю в семь часов каждое утро.'],
      ['Could you help me, please?', 'Не могли бы вы мне помочь, пожалуйста?'],
      ['Where is the nearest bus stop?', 'Где ближайшая автобусная остановка?'],
      ['I would like a cup of tea with milk.', 'Я бы хотел чашку чая с молоком.'],
      ['How much does this jacket cost?', 'Сколько стоит эта куртка?'],
      ['We are going to the beach on Saturday.', 'В субботу мы идём на пляж.'],
      ['My brother is taller than me.', 'Мой брат выше меня.'],
      ['I don\'t understand. Can you repeat that?', 'Я не понимаю. Можете повторить?'],
      ['It is cold today, so take a warm coat.', 'Сегодня холодно, так что возьми тёплое пальто.'],
      ['She has two cats and a dog.', 'У неё две кошки и собака.'],
      ['What time does the shop open?', 'Во сколько открывается магазин?'],
      ['I am learning English because I love travelling.', 'Я учу английский, потому что люблю путешествовать.'],
      ['Let\'s meet in front of the cinema at six.', 'Давай встретимся перед кинотеатром в шесть.'],
      ['Excuse me, is this seat free?', 'Извините, это место свободно?'],
      ['My favourite colour is green.', 'Мой любимый цвет — зелёный.'],
      ['Turn left at the second street.', 'Поверните налево на второй улице.'],
      ['I usually have breakfast at home.', 'Я обычно завтракаю дома.'],
      ['Do you have any brothers or sisters?', 'У тебя есть братья или сёстры?'],
      ['See you tomorrow!', 'Увидимся завтра!'],
    ],
  },
  b1: {
    title: 'Фразы: средний уровень',
    type: 'phrases',
    items: [
      ['I have been working here for three years.', 'Я работаю здесь уже три года.'],
      ['If I had more time, I would learn to play the piano.', 'Если бы у меня было больше времени, я бы научился играть на пианино.'],
      ['She said that she would call me later.', 'Она сказала, что позвонит мне позже.'],
      ['The meeting has been moved to next Thursday.', 'Встречу перенесли на следующий четверг.'],
      ['I\'m looking forward to hearing from you.', 'С нетерпением жду вашего ответа.'],
      ['We ran out of milk, so I went to the shop.', 'У нас закончилось молоко, поэтому я сходил в магазин.'],
      ['He used to smoke, but he gave up last year.', 'Раньше он курил, но в прошлом году бросил.'],
      ['Would you mind closing the window?', 'Вы не против закрыть окно?'],
      ['By the time we arrived, the film had already started.', 'К тому времени, как мы пришли, фильм уже начался.'],
      ['It\'s worth visiting the old part of the city.', 'Стоит посетить старую часть города.'],
      ['I can\'t afford to buy a new car right now.', 'Сейчас я не могу позволить себе новую машину.'],
      ['The more you practise, the better you get.', 'Чем больше практикуешься, тем лучше получается.'],
      ['Could you tell me how to get to the station?', 'Не подскажете, как добраться до вокзала?'],
      ['I\'d rather stay at home tonight.', 'Сегодня вечером я бы лучше остался дома.'],
      ['Despite the rain, we enjoyed our walk.', 'Несмотря на дождь, прогулка нам понравилась.'],
      ['You should have told me earlier!', 'Тебе следовало сказать мне раньше!'],
      ['This book is said to be one of the best of the year.', 'Говорят, эта книга — одна из лучших в этом году.'],
      ['Make sure you switch off the lights when you leave.', 'Не забудь выключить свет, когда будешь уходить.'],
      ['I\'m not used to getting up so early.', 'Я не привык вставать так рано.'],
      ['Let me know if you need anything else.', 'Дай знать, если тебе понадобится что-то ещё.'],
    ],
  },
  b2: {
    title: 'Фразы: продвинутый уровень',
    type: 'phrases',
    items: [
      ['Had I known about the traffic, I would have left earlier.', 'Знай я о пробках, я бы выехал раньше.'],
      ['Not only did she finish the project, but she also presented it brilliantly.', 'Она не только закончила проект, но и блестяще его представила.'],
      ['The proposal, which was rejected last month, is being reconsidered.', 'Предложение, отклонённое в прошлом месяце, пересматривается.'],
      ['It is high time we dealt with this issue.', 'Давно пора заняться этим вопросом.'],
      ['He is thought to have left the country years ago.', 'Считается, что он уехал из страны много лет назад.'],
      ['No sooner had we sat down than the phone rang.', 'Едва мы сели, как зазвонил телефон.'],
      ['I wish I hadn\'t spent so much money on that trip.', 'Жаль, что я потратил столько денег на ту поездку.'],
      ['Whatever happens, don\'t lose sight of your goals.', 'Что бы ни случилось, не упускай из виду свои цели.'],
      ['The results were far better than anyone had expected.', 'Результаты оказались намного лучше, чем кто-либо ожидал.'],
      ['She takes after her father when it comes to music.', 'В том, что касается музыки, она пошла в отца.'],
      ['We need to come up with a solution before Friday.', 'Нам нужно придумать решение до пятницы.'],
      ['On no account should you open this door.', 'Ни в коем случае не открывайте эту дверь.'],
      ['The company has been struggling to keep up with demand.', 'Компания с трудом справляется со спросом.'],
      ['Little did they know what was waiting for them.', 'Они и не подозревали, что их ждёт.'],
      ['I\'d appreciate it if you could get back to me by Monday.', 'Я был бы признателен, если бы вы ответили мне до понедельника.'],
    ],
  },
};
