// Учебные материалы: [английский, русский перевод]
const LESSONS = {
  words: {
    title: 'Базовый уровень', group: 'words', icon: '🌱',
    type: 'words',
    items: [
      ['time', 'время'], ['people', 'люди'], ['year', 'год'], ['way', 'путь, способ'],
      ['day', 'день'], ['man', 'мужчина'], ['thing', 'вещь'], ['woman', 'женщина'],
      ['life', 'жизнь'], ['child', 'ребёнок'], ['world', 'мир'], ['school', 'школа'],
      ['family', 'семья'], ['student', 'студент'], ['group', 'группа'], ['country', 'страна'],
      ['problem', 'проблема'], ['hand', 'рука'], ['part', 'часть'], ['place', 'место'],
      ['week', 'неделя'], ['company', 'компания'], ['question', 'вопрос'], ['work', 'работа'],
      ['night', 'ночь'], ['point', 'точка, смысл'], ['home', 'дом'], ['water', 'вода'],
      ['room', 'комната'], ['mother', 'мать'], ['money', 'деньги'], ['story', 'история'],
      ['month', 'месяц'], ['book', 'книга'], ['job', 'работа, должность'], ['word', 'слово'],
      ['business', 'бизнес'], ['friend', 'друг'], ['city', 'город'], ['idea', 'идея'],
      ['know', 'знать'], ['think', 'думать'], ['make', 'делать'], ['want', 'хотеть'],
      ['give', 'давать'], ['find', 'находить'], ['tell', 'рассказывать'], ['become', 'становиться'],
      ['leave', 'уходить, оставлять'], ['feel', 'чувствовать'], ['bring', 'приносить'], ['begin', 'начинать'],
      ['keep', 'хранить, продолжать'], ['write', 'писать'], ['learn', 'учить'], ['change', 'менять'],
      ['understand', 'понимать'], ['remember', 'помнить'], ['believe', 'верить'], ['happen', 'случаться'],
      ['good', 'хороший'], ['new', 'новый'], ['first', 'первый'], ['last', 'последний'],
      ['long', 'длинный'], ['great', 'великий, отличный'], ['little', 'маленький'], ['different', 'разный'],
      ['small', 'маленький'], ['large', 'большой'], ['young', 'молодой'], ['important', 'важный'],
      ['early', 'ранний'], ['easy', 'лёгкий'], ['strong', 'сильный'], ['beautiful', 'красивый'],
      ['always', 'всегда'], ['never', 'никогда'], ['often', 'часто'], ['already', 'уже'],
      ['father', 'отец'], ['brother', 'брат'], ['sister', 'сестра'], ['house', 'дом (здание)'],
      ['car', 'машина'], ['food', 'еда'], ['bread', 'хлеб'], ['door', 'дверь'],
      ['window', 'окно'], ['table', 'стол'], ['head', 'голова'], ['eye', 'глаз'],
      ['face', 'лицо'], ['street', 'улица'], ['dog', 'собака'], ['cat', 'кошка'],
      ['tree', 'дерево'], ['sun', 'солнце'], ['morning', 'утро'], ['evening', 'вечер'],
      ['go', 'идти, ехать'], ['come', 'приходить'], ['see', 'видеть'], ['eat', 'есть'],
      ['drink', 'пить'], ['sleep', 'спать'], ['open', 'открывать'], ['close', 'закрывать'],
      ['buy', 'покупать'], ['help', 'помогать'], ['ask', 'спрашивать'], ['answer', 'отвечать; ответ'],
      ['happy', 'счастливый'], ['sad', 'грустный'], ['hot', 'горячий, жаркий'], ['cold', 'холодный'],
      ['old', 'старый'], ['big', 'большой'], ['fast', 'быстрый'], ['slow', 'медленный'],
      ['today', 'сегодня'], ['tomorrow', 'завтра'], ['yesterday', 'вчера'], ['now', 'сейчас'],
    ],
  },
  words_mid: {
    title: 'Средний уровень', group: 'words', icon: '🌿',
    type: 'words',
    items: [
      ['achieve', 'достигать'], ['advice', 'совет'], ['afford', 'позволить себе'], ['agree', 'соглашаться'],
      ['amount', 'количество'], ['announce', 'объявлять'], ['anxious', 'тревожный'], ['appearance', 'внешность'],
      ['argue', 'спорить'], ['avoid', 'избегать'], ['behaviour', 'поведение'], ['borrow', 'брать взаймы'],
      ['career', 'карьера'], ['careful', 'осторожный'], ['challenge', 'вызов, трудная задача'], ['compare', 'сравнивать'],
      ['complain', 'жаловаться'], ['confident', 'уверенный'], ['consider', 'рассматривать, считать'], ['decision', 'решение'],
      ['degree', 'степень, градус'], ['describe', 'описывать'], ['develop', 'развивать'], ['disappointed', 'разочарованный'],
      ['environment', 'окружающая среда'], ['equipment', 'оборудование'], ['experience', 'опыт'], ['explain', 'объяснять'],
      ['familiar', 'знакомый'], ['forbid', 'запрещать'], ['frightened', 'испуганный'], ['generous', 'щедрый'],
      ['government', 'правительство'], ['guess', 'угадывать'], ['improve', 'улучшать'], ['include', 'включать'],
      ['increase', 'увеличивать'], ['influence', 'влияние'], ['knowledge', 'знание'], ['lonely', 'одинокий'],
      ['manage', 'справляться, управлять'], ['mention', 'упоминать'], ['neighbour', 'сосед'], ['obvious', 'очевидный'],
      ['opinion', 'мнение'], ['patient', 'терпеливый; пациент'], ['permission', 'разрешение'], ['prefer', 'предпочитать'],
      ['prepare', 'готовить(ся)'], ['prevent', 'предотвращать'], ['promise', 'обещать'], ['reason', 'причина'],
      ['receive', 'получать'], ['recognise', 'узнавать'], ['reduce', 'уменьшать'], ['refuse', 'отказываться'],
      ['relationship', 'отношения'], ['reliable', 'надёжный'], ['suggest', 'предлагать'], ['surprise', 'удивление'],
      ['temperature', 'температура'], ['traffic', 'дорожное движение'], ['weather', 'погода'], ['worried', 'обеспокоенный'],
      ['accept', 'принимать'], ['accident', 'авария, несчастный случай'], ['ancient', 'древний'], ['apologise', 'извиняться'],
      ['appointment', 'встреча, запись (к врачу)'], ['attempt', 'попытка'], ['attitude', 'отношение'], ['benefit', 'польза'],
      ['boring', 'скучный'], ['brave', 'смелый'], ['calm', 'спокойный'], ['celebrate', 'праздновать'],
      ['colleague', 'коллега'], ['community', 'сообщество'], ['confuse', 'путать'], ['contain', 'содержать'],
      ['crowd', 'толпа'], ['deserve', 'заслуживать'], ['destroy', 'разрушать'], ['efficient', 'эффективный'],
      ['emergency', 'чрезвычайная ситуация'], ['encourage', 'поощрять, вдохновлять'], ['exhausted', 'измученный'], ['expensive', 'дорогой'],
      ['flexible', 'гибкий'], ['foreign', 'иностранный'], ['gradually', 'постепенно'], ['honest', 'честный'],
      ['huge', 'огромный'], ['ignore', 'игнорировать'], ['imagine', 'представлять'], ['independent', 'независимый'],
      ['journey', 'путешествие, поездка'], ['lack', 'нехватка'], ['necessary', 'необходимый'], ['nervous', 'нервный'],
      ['offer', 'предлагать; предложение'], ['purpose', 'цель'], ['quality', 'качество'], ['rely', 'полагаться'],
      ['rude', 'грубый'], ['schedule', 'расписание'], ['similar', 'похожий'], ['solution', 'решение'],
      ['success', 'успех'], ['support', 'поддержка'], ['tidy', 'опрятный'], ['urgent', 'срочный'],
    ],
  },
  words_high: {
    title: 'Высокий уровень', group: 'words', icon: '🌳',
    type: 'words',
    items: [
      ['abundant', 'обильный'], ['accomplish', 'выполнять, совершать'], ['acknowledge', 'признавать'], ['adequate', 'достаточный'],
      ['ambiguous', 'двусмысленный'], ['anticipate', 'предвидеть, ожидать'], ['apparent', 'очевидный, кажущийся'], ['arbitrary', 'произвольный'],
      ['assumption', 'предположение'], ['beneficial', 'полезный'], ['comprehensive', 'всесторонний'], ['compromise', 'компромисс'],
      ['consequence', 'последствие'], ['considerable', 'значительный'], ['contemporary', 'современный'], ['controversial', 'спорный'],
      ['convenient', 'удобный'], ['credible', 'правдоподобный'], ['deliberately', 'намеренно'], ['demonstrate', 'демонстрировать'],
      ['deteriorate', 'ухудшаться'], ['diminish', 'уменьшаться'], ['elaborate', 'подробный; развивать'], ['eloquent', 'красноречивый'],
      ['emphasise', 'подчёркивать'], ['encounter', 'сталкиваться'], ['enormous', 'огромный'], ['essential', 'необходимый'],
      ['eventually', 'в конце концов'], ['evidence', 'доказательство'], ['exaggerate', 'преувеличивать'], ['feasible', 'осуществимый'],
      ['fundamental', 'фундаментальный'], ['hesitate', 'колебаться'], ['hypothesis', 'гипотеза'], ['implement', 'внедрять'],
      ['inevitable', 'неизбежный'], ['inherent', 'присущий'], ['initiative', 'инициатива'], ['insight', 'понимание, озарение'],
      ['meticulous', 'дотошный'], ['negotiate', 'вести переговоры'], ['nevertheless', 'тем не менее'], ['notorious', 'печально известный'],
      ['obscure', 'малоизвестный, неясный'], ['perceive', 'воспринимать'], ['persuade', 'убеждать'], ['plausible', 'правдоподобный'],
      ['precise', 'точный'], ['predominantly', 'преимущественно'], ['profound', 'глубокий'], ['reluctant', 'неохотный'],
      ['resilient', 'стойкий'], ['scrutiny', 'тщательная проверка'], ['significant', 'значительный'], ['subsequent', 'последующий'],
      ['substantial', 'существенный'], ['sufficient', 'достаточный'], ['thorough', 'тщательный'], ['ubiquitous', 'вездесущий'],
      ['undermine', 'подрывать'], ['versatile', 'разносторонний'], ['vulnerable', 'уязвимый'], ['whereas', 'тогда как'],
      ['advocate', 'выступать за; сторонник'], ['allegedly', 'предположительно'], ['anomaly', 'аномалия'], ['articulate', 'чётко излагать'],
      ['bias', 'предвзятость'], ['coherent', 'связный, последовательный'], ['collaborate', 'сотрудничать'], ['comply', 'соблюдать, подчиняться'],
      ['concise', 'краткий'], ['consensus', 'единое мнение'], ['contemplate', 'обдумывать'], ['conventional', 'традиционный'],
      ['criteria', 'критерии'], ['discrepancy', 'расхождение'], ['dismiss', 'отвергать; увольнять'], ['disrupt', 'нарушать'],
      ['distinguish', 'различать'], ['empirical', 'эмпирический'], ['endorse', 'одобрять, поддерживать'], ['explicit', 'явный'],
      ['facilitate', 'облегчать, содействовать'], ['fluctuate', 'колебаться'], ['hierarchy', 'иерархия'], ['imminent', 'неминуемый'],
      ['incentive', 'стимул'], ['inadvertently', 'непреднамеренно'], ['integrity', 'честность, целостность'], ['intricate', 'замысловатый'],
      ['mitigate', 'смягчать'], ['notion', 'понятие, представление'], ['paradox', 'парадокс'], ['pragmatic', 'прагматичный'],
      ['prevalent', 'распространённый'], ['prospect', 'перспектива'], ['rationale', 'обоснование'], ['redundant', 'лишний; уволенный по сокращению'],
      ['reinforce', 'укреплять'], ['rigorous', 'строгий, тщательный'], ['simultaneously', 'одновременно'], ['sustainable', 'устойчивый'],
      ['tedious', 'утомительный'], ['tentative', 'предварительный'], ['unprecedented', 'беспрецедентный'], ['viable', 'жизнеспособный'],
    ],
  },
  verbs: {
    title: 'Неправильные глаголы', group: 'words', icon: '🔀',
    type: 'words',
    items: [
      ['go went gone', 'идти'], ['see saw seen', 'видеть'], ['take took taken', 'брать'],
      ['come came come', 'приходить'], ['get got got', 'получать'], ['make made made', 'делать'],
      ['know knew known', 'знать'], ['think thought thought', 'думать'], ['give gave given', 'давать'],
      ['find found found', 'находить'], ['tell told told', 'рассказывать'], ['write wrote written', 'писать'],
      ['speak spoke spoken', 'говорить'], ['break broke broken', 'ломать'], ['buy bought bought', 'покупать'],
      ['bring brought brought', 'приносить'], ['teach taught taught', 'учить (кого-то)'], ['catch caught caught', 'ловить'],
      ['begin began begun', 'начинать'], ['drink drank drunk', 'пить'], ['swim swam swum', 'плавать'],
      ['eat ate eaten', 'есть'], ['fly flew flown', 'летать'], ['forget forgot forgotten', 'забывать'],
      ['choose chose chosen', 'выбирать'], ['wear wore worn', 'носить (одежду)'], ['sleep slept slept', 'спать'],
      ['leave left left', 'уходить'], ['meet met met', 'встречать'], ['pay paid paid', 'платить'],
      ['run ran run', 'бежать'], ['sing sang sung', 'петь'], ['drive drove driven', 'водить машину'],
      ['ride rode ridden', 'ездить верхом, на велосипеде'], ['draw drew drawn', 'рисовать'], ['grow grew grown', 'расти'],
      ['throw threw thrown', 'бросать'], ['hide hid hidden', 'прятать'], ['fall fell fallen', 'падать'],
      ['feel felt felt', 'чувствовать'], ['keep kept kept', 'хранить'], ['lose lost lost', 'терять'],
      ['send sent sent', 'отправлять'], ['spend spent spent', 'тратить'], ['build built built', 'строить'],
      ['sell sold sold', 'продавать'], ['hear heard heard', 'слышать'], ['stand stood stood', 'стоять'],
      ['sit sat sat', 'сидеть'], ['win won won', 'выигрывать'], ['put put put', 'класть'],
      ['cut cut cut', 'резать'], ['read read read', 'читать'], ['steal stole stolen', 'красть'],
      ['understand understood understood', 'понимать'], ['become became become', 'становиться'], ['rise rose risen', 'подниматься'],
    ],
  },
  a1: {
    title: 'Начальный · A1', group: 'levels', icon: '🟢',
    type: 'phrases',
    items: [
      ['My name is Anna and I live in a small town.', 'Меня зовут Анна, и я живу в маленьком городе.'],
      ['I get up at seven o\'clock every morning.', 'Я встаю в семь часов каждое утро.'],
      ['Could you help me, please?', 'Не могли бы вы мне помочь, пожалуйста?'],
      ['Where is the nearest bus stop?', 'Где ближайшая автобусная остановка?'],
      ['I would like a cup of tea with milk.', 'Я бы хотел чашку чая с молоком.'],
      ['How much does this jacket cost?', 'Сколько стоит эта куртка?'],
      ['We are going to the beach on Saturday.', 'В субботу мы идём на пляж.'],
      ['My brother is taller than me.', 'Мой брат выше меня.'],
      ['I don\'t understand. Can you repeat that?', 'Я не понимаю. Можете повторить?'],
      ['It is cold today, so take a warm coat.', 'Сегодня холодно, так что возьми тёплое пальто.'],
      ['She has two cats and a dog.', 'У неё две кошки и собака.'],
      ['What time does the shop open?', 'Во сколько открывается магазин?'],
      ['I am learning English because I love travelling.', 'Я учу английский, потому что люблю путешествовать.'],
      ['Let\'s meet in front of the cinema at six.', 'Давай встретимся перед кинотеатром в шесть.'],
      ['Excuse me, is this seat free?', 'Извините, это место свободно?'],
      ['My favourite colour is green.', 'Мой любимый цвет — зелёный.'],
      ['Turn left at the second street.', 'Поверните налево на второй улице.'],
      ['I usually have breakfast at home.', 'Я обычно завтракаю дома.'],
      ['Do you have any brothers or sisters?', 'У тебя есть братья или сёстры?'],
      ['See you tomorrow!', 'Увидимся завтра!'],
      ['I like reading books in the evening.', 'Мне нравится читать книги по вечерам.'],
      ['My sister works in a hospital.', 'Моя сестра работает в больнице.'],
      ['There is a park near my house.', 'Рядом с моим домом есть парк.'],
      ['What is your phone number?', 'Какой у тебя номер телефона?'],
      ["I'm hungry. Let's have lunch.", 'Я голоден. Давай пообедаем.'],
      ['He plays football every Sunday.', 'Он играет в футбол каждое воскресенье.'],
      ['The weather is nice today.', 'Сегодня хорошая погода.'],
      ['How old are you?', 'Сколько тебе лет?'],
      ["I can swim, but I can't ski.", 'Я умею плавать, но не умею кататься на лыжах.'],
      ['Where do you work?', 'Где ты работаешь?'],
    ],
  },
  b1: {
    title: 'Средний · B1', group: 'levels', icon: '🟡',
    type: 'phrases',
    items: [
      ['I have been working here for three years.', 'Я работаю здесь уже три года.'],
      ['If I had more time, I would learn to play the piano.', 'Если бы у меня было больше времени, я бы научился играть на пианино.'],
      ['She said that she would call me later.', 'Она сказала, что позвонит мне позже.'],
      ['The meeting has been moved to next Thursday.', 'Встречу перенесли на следующий четверг.'],
      ['I\'m looking forward to hearing from you.', 'С нетерпением жду вашего ответа.'],
      ['We ran out of milk, so I went to the shop.', 'У нас закончилось молоко, поэтому я сходил в магазин.'],
      ['He used to smoke, but he gave up last year.', 'Раньше он курил, но в прошлом году бросил.'],
      ['Would you mind closing the window?', 'Вы не против закрыть окно?'],
      ['By the time we arrived, the film had already started.', 'К тому времени, как мы пришли, фильм уже начался.'],
      ['It\'s worth visiting the old part of the city.', 'Стоит посетить старую часть города.'],
      ['I can\'t afford to buy a new car right now.', 'Сейчас я не могу позволить себе новую машину.'],
      ['The more you practise, the better you get.', 'Чем больше практикуешься, тем лучше получается.'],
      ['Could you tell me how to get to the station?', 'Не подскажете, как добраться до вокзала?'],
      ['I\'d rather stay at home tonight.', 'Сегодня вечером я бы лучше остался дома.'],
      ['Despite the rain, we enjoyed our walk.', 'Несмотря на дождь, прогулка нам понравилась.'],
      ['You should have told me earlier!', 'Тебе следовало сказать мне раньше!'],
      ['This book is said to be one of the best of the year.', 'Говорят, эта книга — одна из лучших в этом году.'],
      ['Make sure you switch off the lights when you leave.', 'Не забудь выключить свет, когда будешь уходить.'],
      ['I\'m not used to getting up so early.', 'Я не привык вставать так рано.'],
      ['Let me know if you need anything else.', 'Дай знать, если тебе понадобится что-то ещё.'],
      ["I've been waiting for you for half an hour.", 'Я жду тебя уже полчаса.'],
      ['It depends on the weather.', 'Это зависит от погоды.'],
      ["I'm thinking of changing my job.", 'Я подумываю сменить работу.'],
      ['She is good at solving problems.', 'Она хорошо решает проблемы.'],
      ["We'd better leave now, or we'll be late.", 'Нам лучше выйти сейчас, иначе опоздаем.'],
      ['I forgot to bring my umbrella.', 'Я забыл взять зонт.'],
      ['He apologised for being late.', 'Он извинился за опоздание.'],
      ['Have you decided where to go on holiday?', 'Ты решил, куда поехать в отпуск?'],
      ['There is no point in arguing about it.', 'Нет смысла спорить об этом.'],
      ['I will call you as soon as I arrive.', 'Я позвоню тебе, как только приеду.'],
    ],
  },
  b2: {
    title: 'Продвинутый · B2', group: 'levels', icon: '🔴',
    type: 'phrases',
    items: [
      ['Had I known about the traffic, I would have left earlier.', 'Знай я о пробках, я бы выехал раньше.'],
      ['Not only did she finish the project, but she also presented it brilliantly.', 'Она не только закончила проект, но и блестяще его представила.'],
      ['The proposal, which was rejected last month, is being reconsidered.', 'Предложение, отклонённое в прошлом месяце, пересматривается.'],
      ['It is high time we dealt with this issue.', 'Давно пора заняться этим вопросом.'],
      ['He is thought to have left the country years ago.', 'Считается, что он уехал из страны много лет назад.'],
      ['No sooner had we sat down than the phone rang.', 'Едва мы сели, как зазвонил телефон.'],
      ['I wish I hadn\'t spent so much money on that trip.', 'Жаль, что я потратил столько денег на ту поездку.'],
      ['Whatever happens, don\'t lose sight of your goals.', 'Что бы ни случилось, не упускай из виду свои цели.'],
      ['The results were far better than anyone had expected.', 'Результаты оказались намного лучше, чем кто-либо ожидал.'],
      ['She takes after her father when it comes to music.', 'В том, что касается музыки, она пошла в отца.'],
      ['We need to come up with a solution before Friday.', 'Нам нужно придумать решение до пятницы.'],
      ['On no account should you open this door.', 'Ни в коем случае не открывайте эту дверь.'],
      ['The company has been struggling to keep up with demand.', 'Компания с трудом справляется со спросом.'],
      ['Little did they know what was waiting for them.', 'Они и не подозревали, что их ждёт.'],
      ['I\'d appreciate it if you could get back to me by Monday.', 'Я был бы признателен, если бы вы ответили мне до понедельника.'],
      ['Were it not for your help, I would have given up.', 'Если бы не твоя помощь, я бы сдался.'],
      ['The sooner we start, the sooner we will finish.', 'Чем раньше начнём, тем раньше закончим.'],
      ["He can't have forgotten about the meeting.", 'Не может быть, чтобы он забыл о встрече.'],
      ['Hardly had I arrived when it started to rain.', 'Едва я приехал, как пошёл дождь.'],
      ['It goes without saying that safety comes first.', 'Само собой разумеется, безопасность прежде всего.'],
      ['She is used to working under pressure.', 'Она привыкла работать под давлением.'],
      ["I would rather you didn't tell anyone.", 'Я бы предпочёл, чтобы ты никому не говорил.'],
      ['The project fell through due to a lack of funding.', 'Проект сорвался из-за нехватки финансирования.'],
      ['He is by no means the only one to blame.', 'Он отнюдь не единственный, кто виноват.'],
      ['Should you need any further information, please contact us.', 'Если вам понадобится дополнительная информация, свяжитесь с нами.'],
    ],
  },
  c1: {
    title: 'Свободный · C1', group: 'levels', icon: '🟣',
    type: 'phrases',
    items: [
      ['It remains to be seen whether the new policy will have any real impact.', 'Ещё неизвестно, окажет ли новая политика реальное влияние.'],
      ['Much as I admire his work, I cannot agree with his conclusions.', 'Как бы я ни восхищался его работой, я не могу согласиться с его выводами.'],
      ['The findings call into question much of what we thought we knew.', 'Эти результаты ставят под сомнение многое из того, что мы считали известным.'],
      ['Under no circumstances should confidential data be shared.', 'Ни при каких обстоятельствах нельзя передавать конфиденциальные данные.'],
      ['Were the government to raise taxes, there would be widespread protests.', 'Если бы правительство повысило налоги, начались бы массовые протесты.'],
      ['She was on the verge of giving up when the offer finally came.', 'Она была на грани того, чтобы сдаться, когда наконец пришло предложение.'],
      ['The decision was made in the heat of the moment and he soon regretted it.', 'Решение было принято сгоряча, и вскоре он о нём пожалел.'],
      ['There is a growing body of evidence to suggest that sleep affects memory.', 'Появляется всё больше данных о том, что сон влияет на память.'],
      ['Not until the next morning did we realise what had happened.', 'Только на следующее утро мы поняли, что произошло.'],
      ['He tends to gloss over the weaknesses in his argument.', 'Он склонен замалчивать слабые места в своих доводах.'],
      ['The negotiations came to a standstill over the issue of pay.', 'Переговоры зашли в тупик из-за вопроса об оплате.'],
      ['It is worth bearing in mind that the figures may be misleading.', 'Стоит учитывать, что эти цифры могут вводить в заблуждение.'],
      ['Such was the demand that the tickets sold out within minutes.', 'Спрос был настолько велик, что билеты раскупили за несколько минут.'],
      ['Her remarks were taken out of context and caused a storm of criticism.', 'Её слова вырвали из контекста, и это вызвало шквал критики.'],
      ['Given the circumstances, I think we handled the situation rather well.', 'Учитывая обстоятельства, думаю, мы справились с ситуацией довольно хорошо.'],
      ['The company is poised to become a leader in renewable energy.', 'Компания готова стать лидером в области возобновляемой энергетики.'],
      ['I could not help but notice that you seemed distracted.', 'Я не мог не заметить, что ты казался рассеянным.'],
      ['Whether we like it or not, technology is reshaping the way we work.', 'Нравится нам это или нет, технологии меняют то, как мы работаем.'],
      ['The report sheds light on the hidden costs of fast fashion.', 'Доклад проливает свет на скрытые издержки быстрой моды.'],
      ['It is not so much the money as the principle that bothers me.', 'Меня беспокоят не столько деньги, сколько принцип.'],
      ['By the time the problem came to light, it was far too late to fix it.', 'Когда проблема вскрылась, исправлять её было уже слишком поздно.'],
      ['He made a point of thanking everyone who had been involved.', 'Он специально поблагодарил всех, кто принимал участие.'],
      ['Little by little, the city began to recover from the disaster.', 'Постепенно город начал восстанавливаться после катастрофы.'],
      ['The proposal met with fierce opposition from local residents.', 'Предложение встретило яростное сопротивление местных жителей.'],
      ['On reflection, I think I may have been a little too harsh.', 'Поразмыслив, я думаю, что, возможно, был слишком резок.'],
    ],
  },

  // ---------- Грамматика ----------
  conditionals: {
    title: 'Conditionals', group: 'grammar', icon: '🔁',
    type: 'phrases',
    items: [
      ['If you heat ice, it melts.', 'Если нагреть лёд, он тает.'],
      ['If it rains tomorrow, we will stay at home.', 'Если завтра будет дождь, мы останемся дома.'],
      ["If you don't hurry, you will miss the bus.", 'Если не поторопишься, опоздаешь на автобус.'],
      ['If I were you, I would take the job.', 'На твоём месте я бы согласился на эту работу.'],
      ['If I had more money, I would travel more.', 'Если бы у меня было больше денег, я бы больше путешествовал.'],
      ['What would you do if you won the lottery?', 'Что бы ты сделал, если бы выиграл в лотерею?'],
      ['If I had known, I would have told you.', 'Если бы я знал, я бы тебе сказал.'],
      ["If we had left earlier, we wouldn't have missed the train.", 'Если бы мы вышли раньше, мы бы не опоздали на поезд.'],
      ['If she had studied harder, she would have passed the exam.', 'Если бы она больше занималась, она бы сдала экзамен.'],
      ['If I had taken that job, I would be living in London now.', 'Если бы я тогда согласился на ту работу, сейчас бы жил в Лондоне.'],
      ['Unless you apologise, she will not talk to you.', 'Если ты не извинишься, она не будет с тобой разговаривать.'],
      ['I will lend you the car as long as you drive carefully.', 'Я одолжу тебе машину, если будешь ездить осторожно.'],
      ['If you mix red and blue, you get purple.', 'Если смешать красный и синий, получится фиолетовый.'],
      ["If I see him, I'll tell him to call you.", 'Если увижу его, скажу, чтобы он тебе позвонил.'],
      ['If I lived by the sea, I would swim every day.', 'Если бы я жил у моря, я бы плавал каждый день.'],
      ["If it hadn't rained, we would have gone to the beach.", 'Если бы не пошёл дождь, мы бы пошли на пляж.'],
      ["If you had listened to me, you wouldn't be in trouble now.", 'Если бы ты меня послушал, у тебя сейчас не было бы проблем.'],
      ['Provided that the weather is good, we will have a picnic.', 'При условии хорошей погоды мы устроим пикник.'],
      ['Take a map in case you get lost.', 'Возьми карту на случай, если заблудишься.'],
      ['What would happen if everyone stopped using cars?', 'Что бы случилось, если бы все перестали ездить на машинах?'],
    ],
  },
  present_perfect: {
    title: 'Present Perfect', group: 'grammar', icon: '✅',
    type: 'phrases',
    items: [
      ['I have already finished my homework.', 'Я уже сделал домашнее задание.'],
      ['Have you ever been to Italy?', 'Ты когда-нибудь был в Италии?'],
      ["She hasn't called me yet.", 'Она мне ещё не позвонила.'],
      ['We have lived here since 2015.', 'Мы живём здесь с 2015 года.'],
      ['They have known each other for ten years.', 'Они знают друг друга десять лет.'],
      ["I've just seen your brother in the street.", 'Я только что видел твоего брата на улице.'],
      ['How long have you worked for this company?', 'Сколько ты уже работаешь в этой компании?'],
      ["I've never eaten sushi before.", 'Я никогда раньше не ел суши.'],
      ['Someone has taken my umbrella!', 'Кто-то взял мой зонт!'],
      ['Prices have gone up a lot this year.', 'В этом году цены сильно выросли.'],
      ['I have lost my keys. Can you help me find them?', 'Я потерял ключи. Поможешь найти?'],
      ['Have you finished your report yet?', 'Ты уже закончил отчёт?'],
      ['She has been to London three times.', 'Она была в Лондоне три раза.'],
      ["We haven't seen each other for ages.", 'Мы не виделись целую вечность.'],
      ['This is the best film I have ever seen.', 'Это лучший фильм, который я когда-либо видел.'],
      ['He has just left the office.', 'Он только что ушёл из офиса.'],
      ['I have been learning English for two years.', 'Я учу английский уже два года.'],
      ['It has been raining since morning.', 'Дождь идёт с самого утра.'],
    ],
  },
  passive: {
    title: 'Passive Voice', group: 'grammar', icon: '🔄',
    type: 'phrases',
    items: [
      ['English is spoken all over the world.', 'На английском говорят по всему миру.'],
      ['The bridge was built in 1890.', 'Мост был построен в 1890 году.'],
      ['My bike has been stolen.', 'Мой велосипед украли.'],
      ['The letters are delivered every morning.', 'Письма доставляют каждое утро.'],
      ['The new hospital will be opened next year.', 'Новую больницу откроют в следующем году.'],
      ['The room is being cleaned right now.', 'Комнату сейчас убирают.'],
      ['This film was directed by a young woman.', 'Этот фильм сняла молодая женщина.'],
      ['The meeting has been cancelled.', 'Встречу отменили.'],
      ['Smoking is not allowed in the building.', 'Курить в здании запрещено.'],
      ['He was born in a small village.', 'Он родился в маленькой деревне.'],
      ['The windows are cleaned once a month.', 'Окна моют раз в месяц.'],
      ['The thief was caught by the police.', 'Вора поймала полиция.'],
      ['The results will be announced tomorrow.', 'Результаты объявят завтра.'],
      ['The car is being repaired at the moment.', 'Машину сейчас ремонтируют.'],
      ['All the tickets have been sold.', 'Все билеты проданы.'],
      ['The castle was destroyed during the war.', 'Замок был разрушен во время войны.'],
      ['This problem must be solved as soon as possible.', 'Эту проблему нужно решить как можно скорее.'],
      ['I was told to wait outside.', 'Мне сказали подождать снаружи.'],
    ],
  },
  reported: {
    title: 'Reported Speech', group: 'grammar', icon: '💬',
    type: 'phrases',
    items: [
      ['She said that she was tired.', 'Она сказала, что устала.'],
      ['He told me that he had lost his keys.', 'Он сказал мне, что потерял ключи.'],
      ['They said they would come later.', 'Они сказали, что придут позже.'],
      ['She asked me where I lived.', 'Она спросила, где я живу.'],
      ['He asked if I could help him.', 'Он спросил, могу ли я ему помочь.'],
      ['My mother told me to be careful.', 'Мама сказала мне быть осторожным.'],
      ['The teacher asked us not to talk.', 'Учитель попросил нас не разговаривать.'],
      ['He said he had never seen the sea.', 'Он сказал, что никогда не видел моря.'],
      ['She wanted to know what time the train left.', 'Она хотела знать, во сколько уходит поезд.'],
      ['He promised that he would call me.', 'Он пообещал, что позвонит мне.'],
      ['He said that he was going to move to Berlin.', 'Он сказал, что собирается переехать в Берлин.'],
      ['She told me she had already eaten.', 'Она сказала мне, что уже поела.'],
      ['They asked us why we were late.', 'Они спросили нас, почему мы опоздали.'],
      ['He wondered whether the shop was still open.', 'Ему было интересно, открыт ли ещё магазин.'],
      ['The doctor advised me to rest.', 'Врач посоветовал мне отдохнуть.'],
      ['She reminded me to lock the door.', 'Она напомнила мне запереть дверь.'],
      ['He admitted that he had made a mistake.', 'Он признал, что совершил ошибку.'],
      ['I asked her how long she had been waiting.', 'Я спросил её, как долго она ждёт.'],
    ],
  },
  modals: {
    title: 'Modal verbs', group: 'grammar', icon: '🔑',
    type: 'phrases',
    items: [
      ['You must wear a seat belt.', 'Ты обязан пристегнуться.'],
      ["You don't have to come if you don't want to.", 'Можешь не приходить, если не хочешь.'],
      ['You should see a doctor.', 'Тебе стоит сходить к врачу.'],
      ['Can I open the window?', 'Можно открыть окно?'],
      ['She might be at home now.', 'Возможно, она сейчас дома.'],
      ['He must be very tired after the trip.', 'Он, должно быть, очень устал после поездки.'],
      ["You mustn't touch this button.", 'Эту кнопку трогать нельзя.'],
      ['Could you speak a little slower, please?', 'Не могли бы вы говорить чуть медленнее?'],
      ['I could swim when I was five.', 'Я умел плавать, когда мне было пять.'],
      ['You should have told me about it.', 'Тебе следовало рассказать мне об этом.'],
      ['May I come in?', 'Можно войти?'],
      ['We need to buy some milk.', 'Нам нужно купить молока.'],
      ["You needn't worry about it.", 'Тебе не нужно об этом беспокоиться.'],
      ["It can't be true!", 'Не может быть!'],
      ['Would you like some coffee?', 'Хотите кофе?'],
      ['She may not come to the party.', 'Она, возможно, не придёт на вечеринку.'],
      ['I had to work late yesterday.', 'Вчера мне пришлось работать допоздна.'],
      ['You ought to apologise to her.', 'Тебе следует извиниться перед ней.'],
    ],
  },

  // ---------- Ситуации ----------
  airport: {
    title: 'В аэропорту и самолёте', group: 'situations', icon: '✈️',
    type: 'phrases',
    items: [
      ['Where is the check-in desk for flight BA 245?', 'Где стойка регистрации на рейс BA 245?'],
      ['I would like a window seat, please.', 'Я бы хотел место у окна, пожалуйста.'],
      ['How many bags can I check in?', 'Сколько сумок я могу сдать в багаж?'],
      ['Is this bag small enough to take on board?', 'Эту сумку можно взять в салон?'],
      ['Here is my passport and boarding pass.', 'Вот мой паспорт и посадочный талон.'],
      ['Which gate does the flight leave from?', 'От какого выхода вылетает рейс?'],
      ['The flight has been delayed by two hours.', 'Рейс задержали на два часа.'],
      ['Please fasten your seat belt.', 'Пожалуйста, пристегните ремень.'],
      ['Could I have some water, please?', 'Можно мне воды, пожалуйста?'],
      ['Excuse me, I think you are in my seat.', 'Извините, кажется, вы сидите на моём месте.'],
      ['My luggage did not arrive.', 'Мой багаж не прилетел.'],
      ['Where can I get a taxi to the city centre?', 'Где можно взять такси до центра города?'],
      ['Do I need to take my laptop out of the bag?', 'Мне нужно достать ноутбук из сумки?'],
      ['Is there a charge for extra baggage?', 'За лишний багаж нужно доплачивать?'],
      ['What time does boarding start?', 'Во сколько начинается посадка?'],
      ['Could you help me put my bag in the overhead locker?', 'Не могли бы вы помочь положить сумку на полку?'],
      ["I'd like the chicken, please.", 'Мне курицу, пожалуйста.'],
      ['I have a connecting flight to Rome.', 'У меня стыковочный рейс в Рим.'],
      ['Where is the baggage claim?', 'Где выдача багажа?'],
      ['I have nothing to declare.', 'Мне нечего декларировать.'],
    ],
  },
  station: {
    title: 'На вокзале', group: 'situations', icon: '🚆',
    type: 'phrases',
    items: [
      ['A return ticket to Manchester, please.', 'Билет до Манчестера туда и обратно, пожалуйста.'],
      ['What time is the next train to Oxford?', 'Во сколько следующий поезд до Оксфорда?'],
      ['Which platform does the train leave from?', 'С какой платформы отправляется поезд?'],
      ['Do I need to change trains?', 'Мне нужно делать пересадку?'],
      ['How long does the journey take?', 'Сколько времени занимает поездка?'],
      ['Is this seat taken?', 'Это место занято?'],
      ['The train is running ten minutes late.', 'Поезд опаздывает на десять минут.'],
      ['Where can I leave my luggage?', 'Где можно оставить багаж?'],
      ['Does this train stop at Cambridge?', 'Этот поезд останавливается в Кембридже?'],
      ['I have missed my train. What should I do?', 'Я опоздал на поезд. Что мне делать?'],
      ['Two single tickets to Brighton, please.', 'Два билета в одну сторону до Брайтона, пожалуйста.'],
      ['Is there a discount for students?', 'Есть скидка для студентов?'],
      ['Where is the ticket office?', 'Где билетная касса?'],
      ['The train to Leeds has been cancelled.', 'Поезд до Лидса отменили.'],
      ['Which carriage is my seat in?', 'В каком вагоне моё место?'],
      ['Can I have a timetable, please?', 'Можно мне расписание?'],
      ['Please mind the gap between the train and the platform.', 'Будьте осторожны: между вагоном и платформой есть зазор.'],
      ['How often do trains run to the airport?', 'Как часто ходят поезда в аэропорт?'],
    ],
  },
  cafe: {
    title: 'В кафе и ресторане', group: 'situations', icon: '☕',
    type: 'phrases',
    items: [
      ['A table for two, please.', 'Столик на двоих, пожалуйста.'],
      ['Could we see the menu, please?', 'Можно нам меню?'],
      ['What do you recommend?', 'Что вы посоветуете?'],
      ["I'll have the soup and a green salad.", 'Мне суп и зелёный салат.'],
      ['Can I have a cappuccino to take away?', 'Можно капучино с собой?'],
      ['Is this dish very spicy?', 'Это блюдо очень острое?'],
      ["I'm allergic to nuts.", 'У меня аллергия на орехи.'],
      ['Could I have some more bread, please?', 'Можно ещё хлеба, пожалуйста?'],
      ['Excuse me, this is not what I ordered.', 'Извините, я заказывал не это.'],
      ['Can we have the bill, please?', 'Можно счёт, пожалуйста?'],
      ['Can I pay by card?', 'Можно оплатить картой?'],
      ['Keep the change.', 'Сдачи не надо.'],
      ['Do you have a vegetarian menu?', 'У вас есть вегетарианское меню?'],
      ['Could we sit by the window?', 'Можно нам сесть у окна?'],
      ["I'd like my steak medium, please.", 'Мне стейк средней прожарки, пожалуйста.'],
      ['Could I have a glass of water with no ice?', 'Можно стакан воды без льда?'],
      ['We are ready to order.', 'Мы готовы сделать заказ.'],
      ['Everything was delicious, thank you.', 'Всё было очень вкусно, спасибо.'],
      ['Is service included?', 'Обслуживание включено в счёт?'],
      ['Can we split the bill?', 'Можно разделить счёт?'],
    ],
  },
  hotel: {
    title: 'В отеле', group: 'situations', icon: '🏨',
    type: 'phrases',
    items: [
      ['I have a reservation under the name Smith.', 'У меня бронь на фамилию Смит.'],
      ['Do you have a double room for two nights?', 'У вас есть двухместный номер на две ночи?'],
      ['Is breakfast included?', 'Завтрак включён?'],
      ['What time is check-out?', 'Во сколько выезд?'],
      ['What is the Wi-Fi password?', 'Какой пароль от Wi-Fi?'],
      ['The air conditioning in my room is not working.', 'В моём номере не работает кондиционер.'],
      ['Could I have an extra towel, please?', 'Можно мне ещё одно полотенце?'],
      ['Can you call a taxi for me?', 'Вызовите мне, пожалуйста, такси.'],
      ['Can I leave my bags here until the evening?', 'Можно оставить сумки здесь до вечера?'],
      ['I would like to extend my stay for one more night.', 'Я бы хотел продлить проживание ещё на одну ночь.'],
      ['Is there a lift in the building?', 'В здании есть лифт?'],
      ['Could I have a room with a sea view?', 'Можно номер с видом на море?'],
      ['What time is breakfast served?', 'Во сколько подают завтрак?'],
      ['Could you wake me up at seven, please?', 'Не могли бы вы разбудить меня в семь?'],
      ["I've lost my room key.", 'Я потерял ключ от номера.'],
      ['There is no hot water in the bathroom.', 'В ванной нет горячей воды.'],
      ['Is there a safe in the room?', 'В номере есть сейф?'],
      ["I'd like to check out, please.", 'Я хотел бы выехать, пожалуйста.'],
    ],
  },
  shop: {
    title: 'В магазине', group: 'situations', icon: '🛍️',
    type: 'phrases',
    items: [
      ["I'm just looking, thank you.", 'Я просто смотрю, спасибо.'],
      ['Do you have this in a smaller size?', 'У вас есть это на размер меньше?'],
      ['Can I try it on?', 'Можно примерить?'],
      ['Where are the fitting rooms?', 'Где примерочные?'],
      ['How much is this?', 'Сколько это стоит?'],
      ['Is there a discount on this item?', 'На этот товар есть скидка?'],
      ["I'll take it.", 'Я возьму это.'],
      ['Could I have a receipt, please?', 'Можно чек, пожалуйста?'],
      ['I would like to return this jacket.', 'Я бы хотел вернуть эту куртку.'],
      ['Do you have a bag?', 'У вас есть пакет?'],
      ['Do you have this in another colour?', 'У вас есть это другого цвета?'],
      ["It's too expensive for me.", 'Для меня это слишком дорого.'],
      ['Where can I find the milk?', 'Где найти молоко?'],
      ['Are these shoes on sale?', 'На эти туфли есть скидка?'],
      ['Can I pay in cash?', 'Можно заплатить наличными?'],
      ['Could you wrap it as a present?', 'Можете упаковать это как подарок?'],
      ['What time do you close?', 'Во сколько вы закрываетесь?'],
      ["It doesn't fit me.", 'Мне это не подходит по размеру.'],
    ],
  },
  doctor: {
    title: 'У врача', group: 'situations', icon: '🩺',
    type: 'phrases',
    items: [
      ["I'd like to make an appointment with a doctor.", 'Я хотел бы записаться к врачу.'],
      ["I don't feel well.", 'Я плохо себя чувствую.'],
      ['I have a headache and a sore throat.', 'У меня болит голова и горло.'],
      ['I have had a high temperature since yesterday.', 'У меня высокая температура со вчерашнего дня.'],
      ['It hurts when I walk.', 'Мне больно ходить.'],
      ['Are you allergic to any medicine?', 'У вас есть аллергия на какие-нибудь лекарства?'],
      ['Take two tablets three times a day.', 'Принимайте по две таблетки три раза в день.'],
      ['Where is the nearest pharmacy?', 'Где ближайшая аптека?'],
      ['Do I need a prescription for this?', 'Для этого нужен рецепт?'],
      ['Please call an ambulance!', 'Пожалуйста, вызовите скорую!'],
      ["I've been coughing for a week.", 'Я кашляю уже неделю.'],
      ['I feel dizzy and sick.', 'У меня кружится голова и тошнит.'],
      ['I think I have broken my arm.', 'Кажется, я сломал руку.'],
      ['How long should I take this medicine?', 'Как долго мне принимать это лекарство?'],
      ['Should I stay in bed?', 'Мне нужно соблюдать постельный режим?'],
      ['I need something for a cold.', 'Мне нужно что-нибудь от простуды.'],
      ['My stomach hurts.', 'У меня болит живот.'],
      ['When should I come back for a check-up?', 'Когда мне прийти на повторный осмотр?'],
    ],
  },
  city: {
    title: 'В городе', group: 'situations', icon: '🗺️',
    type: 'phrases',
    items: [
      ['Excuse me, how do I get to the museum?', 'Извините, как пройти к музею?'],
      ['Is it far from here?', 'Это далеко отсюда?'],
      ["It's about ten minutes on foot.", 'Это примерно десять минут пешком.'],
      ['Go straight on and turn right at the traffic lights.', 'Идите прямо и поверните направо на светофоре.'],
      ["It's opposite the bank.", 'Это напротив банка.'],
      ['Which bus goes to the city centre?', 'Какой автобус идёт в центр города?'],
      ['Where can I buy a ticket?', 'Где можно купить билет?'],
      ['Could you show me on the map?', 'Не могли бы вы показать на карте?'],
      ["I'm lost. Can you help me?", 'Я заблудился. Можете помочь?'],
      ['Is there a supermarket near here?', 'Здесь поблизости есть супермаркет?'],
      ['Where is the nearest metro station?', 'Где ближайшая станция метро?'],
      ['Take the second turning on the left.', 'Поверните во второй поворот налево.'],
      ["It's just around the corner.", 'Это прямо за углом.'],
      ['How much is a ticket to the city centre?', 'Сколько стоит билет до центра?'],
      ['Can I walk there?', 'Туда можно дойти пешком?'],
      ['Is this the right way to the station?', 'Я правильно иду к вокзалу?'],
      ['Could you tell me where the post office is?', 'Не подскажете, где почта?'],
      ['Cross the road and go past the church.', 'Перейдите дорогу и пройдите мимо церкви.'],
    ],
  },
};

// Группы уроков в меню выбора, по порядку
const GROUPS = [
  { id: 'words', title: 'Слова' },
  { id: 'levels', title: 'Фразы по уровню' },
  { id: 'grammar', title: 'Грамматика' },
  { id: 'situations', title: 'Ситуации' },
];
